site_name: Professional Python Programming
site_url: https://pythonbook.org
repo_url: https://github.com/ying-teaching/python-book
repo_name: 'GitHub'

theme:
  name: material
  features:
    - navigation.sections
    - navigation.footer

exclude_docs: |
  *.ipynb

nav:
  - Home: index.md
  - 'Part I. Python Programming':
      - 'Chapter 1: Introduction':
          - ch01_introduction/notes/introduction.md
          - ch01_introduction/notes/crash_course.md
      - 'Chapter 2: Variable and Expression':
          - ch02_variable/notes/variables.md
          - ch02_variable/notes/expression_statement.md
          - ch02_variable/notes/turtle_introduction.md
      - 'Chapter 3: Branch': ch03_branch/notes/branch.md
      - 'Chapter 4: Loop': ch04_loop/notes/loop.md
      - 'Chapter 5: Function': ch05_function/notes/function.md
      - 'Chapter 6 Collection (TBC)': tbc.md
      - 'Chapter 7 Class (TBC)': tbc.md
      - 'Chapter 8 Exception (TBC)': tbc.md
      - 'Chapter 9 Module (TBC)': tbc.md
      - 'Chapter 10 File (TBC)': tbc.md
  - 'Part II. Professional Programming':
      - 'Chapter 11: Test (TBC)': tbc.md
      - 'Chapter 12: Data Model (TBC)': tbc.md
      - 'Chapter 13: Log (TBC)': tbc.md
      - 'Chapter 14: Type (TBC)': tbc.md
      - 'Chapter 15: Performance (TBC)': tbc.md
  - 'Part III. Algorithm Thinking':
      - 'Chapter 16: A Web Site':
          - ch16_django/notes/basic_django.md
          - ch16_django/notes/advanced_django.md
      - 'Chapter 17: A Lisp Interpreter (TBC)': tbc.md
  - Appendix:
      - 'Development Tools':
          - 'Command Line Interface': appendix/command_line.md
          - 'Python Installation': appendix/install_python.md
          - 'VS Code': appendix/vscode_python.md
          - 'Git and GitHub': appendix/git_and_github.md
      - 'Learn Programming':
          - 'Learn Programming': appendix/misc/learn_programming.md
          - 'Rust and Cryptography': appendix/misc/rust_cryptography.md

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: Copyright &copy; 2023 Ying Liu
extra:
  generator: false
