site_name: My Docs

site_name: Pragmatic Python Programming

theme:
  name: material
  features:
    - navigation.sections

exclude_docs: |
  *.ipynb

nav:
  - Home: index.md
  - Slides: slides.md
  - 'Part I. Python Programming':
      - 'Chapter 1: Introduction':
          - ch01_introduction/notes/introduction.md
          - ch01_introduction/notes/crash_course.md
      - 'Chapter 2: Variable and Expression':
          - ch02_variable/notes/variables.md
          - ch02_variable/notes/expression_statement.md
          - ch02_variable/notes/turtle_introduction.md
      - 'Chapter 3: Branch': ch03_branch/notes/branch.md
      - 'Chapter 4: Loop': ch04_loop/notes/loop.md
      - 'Chapter 5: Function': ch05_function/notes/function.md
      - 'Chapter 6': tbc.md
      - 'Chapter 7': tbc.md
      - 'Chapter 8': tbc.md
      - 'Chapter 9': tbc.md
      - 'Chapter 10': tbc.md
  - 'Part II. Pragmatic Programming':
      - 'Chapter 11: Test': tbc.md
      - 'Chapter 12: Data Model': tbc.md
      - 'Chapter 13: Log': tbc.md
      - 'Chapter 14: Type': tbc.md
      - 'Chapter 15: Performance': tbc.md
  - 'Part III. Algorithm Thinking':
      - 'Chapter 16: A Web Site': tbc.md
      - 'Chapter 17: A Lisp Interpreter': tbc.md
  - Appendix:
      - 'Development Tools':
          - 'Command Line Interface': appendix/command_line.md
          - 'Python Installation': appendix/install_python.md
          - 'VS Code': appendix/vscode_python.md
          - 'Git and GitHub': appendix/git_and_github.md
      - 'Learn Programming':
          - 'Learn Programming': appendix/misc/learn_programming.md
          - 'Rust and Cryptography': appendix/misc/rust_cryptography.md


markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
